[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
usdc_split = "7JP1EJH9kP1MQhnCJZztpikJaQpJB5g5bNr1z1fQcQaP"

[programs.devnet]
usdc_split = "7JP1EJH9kP1MQhnCJZztpikJaQpJB5g5bNr1z1fQcQaP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
